### ISSUE TITLE
Sample settings is not able to check after refresh

### ISSUE THREAD

**Issue by JialinXin** [VSChina/iot-hub-e2e-diagnostic#9]
Once user refresh the page, the sampling settings is back to default value. He won't know about current settings.

![image](https://user-images.githubusercontent.com/15338714/26909816-e9c471ac-4c35-11e7-94da-74f85dab6f23.png)

**Comment by formulahendry** [comment]
It is by design, since we could set device1 as 50 and set device2 as 60. We could not show the current settings.
